version: "3"
services:
  eureka-server:
    build: eureka-server/
    container_name: fit-eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761
      
  api-gateway:
    build: api-gateway/
    container_name: fit-api-gateway
    depends_on:
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8005:8005


      
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    hostname: localhost
    ports:
      - "27017:27017"  
      
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql-container
    network_mode: "host"
    hostname: localhost
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      
  authentication-service:
    container_name: fit-Authentication-service
    build: Authentication-service/
    network_mode: "host"
    hostname: localhost
    ports:
      - 8020:8020
    depends_on:
      - eureka-server
      - mysql
    restart: always 

  chat-service:
    container_name: fit-Chat-service
    build: Chat-service/
    network_mode: "host"
    hostname: localhost
    ports:
      - 8021:8021
    depends_on:
      - eureka-server
      - mongodb
    restart: always 
    
  gym-service:
    container_name: fit-Gym-service
    build: Gym-service/
    network_mode: "host"
    hostname: localhost
    ports:
      - 8023:8023
    depends_on:
      - eureka-server
      - mongodb
    restart: always 
    
  notification-service:
    container_name: fit-Notification-service
    build: Notification-service/
    network_mode: "host"
    hostname: localhost
    ports:
      - 8024:8024
    depends_on:
      - eureka-server
    restart: always
    
  payment-service:
    container_name: fit-Payment-service
    build: Payment-service/
    network_mode: "host"
    hostname: localhost
    ports:
      - 8025:8025
    depends_on:
      - eureka-server
      - mysql
    restart: always
    
  user-service:
    container_name: fit-User-service
    build: User-service/
    network_mode: "host"
    hostname: localhost
    ports:
      - 8027:8027
    depends_on:
      - eureka-server
      - mysql
    restart: always
    
  product-webapp:
    build: product-webapp-service/
    image: fit-product-webapp-service
    depends_on:
      - eureka-server
      - api-gateway
    restart: always
    container_name: product-webapp-service
    network_mode: "host"
    hostname: localhost
    ports:
      - "8026:8026"
      
  feedback-service:
    container_name: fit-Feedback-service
    build: Feedback-service/
    network_mode: "host"
    hostname: localhost
    ports:
      - 8022:8022
    depends_on:
      - eureka-server
      - mongodb
    restart: always
